//
//      Base class for module system result symbols.
//
#ifndef _resultSymbol_hh_
#define _resultSymbol_hh_
#include "freeSymbol.hh"
#include "AU_Symbol.hh"

class ResultSymbol : public FreeSymbol
{
  NO_COPYING(ResultSymbol);

public:
  ResultSymbol(int id, int nrArgs);

protected:
  MetaLevel* getMetaLevel() const;
  Symbol* getTransformOp(const ConnectedComponent* qidKind);
  DagNode* makeStartDag(const Vector<ImportModule*>& inputModules,
			DagNode* metaOptions,
			const Vector<View*>& inputViews,
			PointerMap& qidMap);
  bool multipleViews(Symbol* s) const;
  bool noViews(Symbol* s) const;
  bool multipleModules(Symbol* s) const;
  bool noModules(Symbol* s) const;
  void handleMessageList(DagNode* messages, LineNumber lineNumber) const;
  DagNode* upModuleList(bool flat,
			const Vector<ImportModule*>& inputModules,
			PointerMap& qidMap) const;
  DagNode* upViewList(const Vector<View*>& inputViews, PointerMap& qidMap) const;

private:
  bool attachSymbol(const char* purpose, Symbol* symbol);
  void getSymbolAttachments(Vector<const char*>& purposes,
			    Vector<Symbol*>& symbols);
  void copyAttachments(Symbol* original, SymbolMap* map);

  bool hasTransformFlag(Symbol* symbol);
  bool hasGoodDomain(Symbol* symbol, Vector<const ConnectedComponent*>& domain);

  void handleMessage(DagNode* message, LineNumber lineNumber) const;
  static Rope colorize(const Rope& text);
  //
  //    View result signature (generated by macro expansion).
  //
#define MACRO(SymbolName, SymbolClass)	\
  SymbolClass* SymbolName = nullptr;
#include "resultSignature.cc"
#undef MACRO

  Symbol* cachedTransformOp = nullptr;
};

inline bool
ResultSymbol::multipleViews(Symbol* s) const
{
  return s == viewListSymbol;
}

inline bool
ResultSymbol::noViews(Symbol* s) const
{
  return s == nilViewListSymbol;
}

inline bool
ResultSymbol::multipleModules(Symbol* s) const
{
  return s == moduleListSymbol;
}

inline bool
ResultSymbol::noModules(Symbol* s) const
{
  return s == nilModuleListSymbol;
}

#endif
