/*

    This file is part of the Maude 3 interpreter.

    Copyright 2026 SRI International, Menlo Park, CA 94025, USA.

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

*/

//
//      Class for transform result symbols.
//
//	They don't have any special operational semantics but serve to
//	identify kinds used for user-defined module operations and to
//	hold related data.
//
#ifndef _transformResultSymbol_hh_
#define _transformResultSymbol_hh_
#include "freeSymbol.hh"

class TransformResultSymbol : public FreeSymbol
{
  NO_COPYING(TransformResultSymbol);

public:
  TransformResultSymbol(int id);

private:
  ~TransformResultSymbol();

  bool attachSymbol(const char* purpose, Symbol* symbol);
  void copyAttachments(Symbol* original, SymbolMap* map);
  void getSymbolAttachments(Vector<const char*>& purposes,
			    Vector<Symbol*>& symbols);

  //
  //	Transform result signature (generated by macro expansion).
  //
#define MACRO(SymbolName, SymbolClass)	\
  SymbolClass* SymbolName;
#include "transformResultSignature.cc"
#undef MACRO

  MetaLevel* metaLevel;
  FreeSymbol* cachedImplicitTransformer;
}
