/*

    This file is part of the Maude 3 interpreter.

    Copyright 2026 SRI International, Menlo Park, CA 94025, USA.

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

*/

//
//      Class for transform result symbols.
//
//	They don't have any special operational semantics but serve to
//	identify kinds used for user-defined module operations and to
//	hold related data.
//
#ifndef _transformResultSymbol_hh_
#define _transformResultSymbol_hh_
#include "freeSymbol.hh"

class TransformResultSymbol : public FreeSymbol
{
  NO_COPYING(TransformResultSymbol);

public:
  TransformResultSymbol(int id);
  
  ImportModule* makeTransformation(int newModuleName,
				   int opName,
				   const Vector<ImportModule*>& inputModules,
				   const Vector<int>& optionVec);

private:
  ~TransformResultSymbol();

  bool attachData(const Vector<Sort*>& opDeclaration,
		  const char* purpose,
		  const Vector<const char*>& data);
  void getDataAttachments(const Vector<Sort*>& opDeclaration,
			  Vector<const char*>& purposes,
			  Vector<Vector<const char*>>& data);
  bool attachSymbol(const char* purpose, Symbol* symbol);
  void getSymbolAttachments(Vector<const char*>& purposes,
			    Vector<Symbol*>& symbols);
  void copyAttachments(Symbol* original, SymbolMap* map);

  void handleMessage(DagNode* message);

  //
  //	Transform result signature (generated by macro expansion).
  //
#define MACRO(SymbolName, SymbolClass)	\
  SymbolClass* SymbolName = nullptr;
#include "transformResultSignature.cc"
#undef MACRO

  MetaLevel* metaLevel = nullptr;
  Symbol* cachedTransformOp = nullptr;  // for implicit transform ops
  //ConnectedComponent* moduleKind = nullptr;  domainComponent(0)
  //ConnectedComponent* qidKind = nullptr;
  //ConnectedComponent* transformResultKind = nullptr; rangeComponent()
};

#endif
