#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/badModuleAdd.maude -no-banner \
  > badModuleAdd.out 2>&1

diff $srcdir/badModuleAdd.expected badModuleAdd.out > /dev/null 2>&1
