#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/badViewAdd.maude -no-banner \
  > badViewAdd.out 2>&1

diff $srcdir/badViewAdd.expected badViewAdd.out > /dev/null 2>&1
