#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/defaultView.maude -no-banner \
  > defaultView.out 2>&1

diff $srcdir/defaultView.expected defaultView.out > /dev/null 2>&1
