set show timing off .

***
***	Test generation of default views for modules.
***

fmod TEST is
  pr SET{@[NAT]} .
endfm

red 5, 6, 7, 6 .

fmod TEST2{X :: TRIV} is
  pr SET{@[LIST]{X}} .
endfm

fmod TEST3 is
  pr TEST2{@[QID]} .
endfm

red 'a 'b 'c, 'a 'd, 'b 'b 'b .
red ('a 'b 'c, 'a 'd, 'b 'b 'b) \ 'a 'd .

make FOO1 is LIST{@[NAT](NzNat)} endm
show sorts .

make FOO2 is LIST{@[NAT](Int)} endm

make FOO3 is LIST{@[NAT](`{not a sort`})} endm

fmod FOO is
  sorts F{A} G{A,B} A`B`C .
endfm

make BAR1 is LIST{@[FOO]} endm

make BAR2 is LIST{@[FOO](A`B`C)} endm
show sorts .

make BAR3 is LIST{@[FOO](F{A})} endm
show sorts .

make BAR4 is LIST{@[FOO](G{A,B})} endm
show sorts .

make BAR5 is LIST{@[FOO](F{A}, G{A,B})} endm

make StringList is LIST{@[STRING]} endm
show sorts .
red "a" "bc" "de" .

make CharList is LIST{@[STRING](Char)} endm
show sorts .
red "a" "b" "c" "d" "e" .

fmod FOO4 is
  pr SET{@[TUPLE(2)]{Nat, Nat}} .
endfm

show sorts .

fmod FOO5 is
  pr SET{@[TUPLE(2){Nat, Nat}]} .
endfm

show sorts .

fmod FOO6{X :: TRIV, Y :: TRIV} is
  pr TUPLE(2){@[TUPLE(3)]{X, X, @[TUPLE(2)]{Y, Y}}, Y} .
endfm

show sorts .

fmod FOO7 is
  pr FOO6{@[NAT](NzNat), @[STRING]} .
endfm

show sorts .

make FOO8 is LIST{@[SET{@[NAT]}]} endm
show sorts .

fmod FOO9{X :: TRIV, Y :: TRIV} is
  pr LIST{@[SET]{@[TUPLE(2)]{X, Y}}} .
endfm

show sorts .

fmod FOO10 is
  pr FOO9{@[NAT], @[STRING]} .
endfm

show sorts .

red (3, "three"), (4, "four"), (5, "five") .

red ((3, "three"), (4, "four"), (5, "five")) ((6, "six"), (7, "seven")) .
