#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/dropEquations.maude -no-banner \
  > dropEquations.out 2>&1

diff $srcdir/dropEquations.expected dropEquations.out > /dev/null 2>&1
