TESTS = \
	tuple \
	dropEquations \
	defaultView \
	badModuleAdd \
	badViewAdd

MAUDE_FILES = \
	tuple.maude \
	dropEquations.maude \
	defaultView.maude \
	badModuleAdd.maude \
	badViewAdd.maude

RESULT_FILES = \
	tuple.expected \
	dropEquations.expected \
	defaultView.expected \
	badModuleAdd.expected \
	badViewAdd.expected

EXTRA_DIST = $(TESTS) $(MAUDE_FILES) $(RESULT_FILES)
