#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/ACU_TreeVariableSubproblem.maude -no-banner \
  > ACU_TreeVariableSubproblem.out 2>&1

diff $srcdir/ACU_TreeVariableSubproblem.expected ACU_TreeVariableSubproblem.out > /dev/null 2>&1
