#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/attributeOverparsing.maude -no-banner -no-advise \
  > attributeOverparsing.out 2>&1

diff $srcdir/attributeOverparsing.expected attributeOverparsing.out > /dev/null 2>&1
