#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/badOmod.maude -no-banner \
  > badOmod.out 2>&1

diff $srcdir/badOmod.expected badOmod.out > /dev/null 2>&1
