#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/badStatement.maude -no-banner \
  > badStatement.out 2>&1

diff $srcdir/badStatement.expected badStatement.out > /dev/null 2>&1
