#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/operatorNames.maude -no-banner \
  > operatorNames.out 2>&1

diff $srcdir/operatorNames.expected operatorNames.out > /dev/null 2>&1
