#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/otfVariables.maude -no-banner \
  > otfVariables.out 2>&1

diff $srcdir/otfVariables.expected otfVariables.out > /dev/null 2>&1
