#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/otfVariables2.maude -no-banner \
  > otfVariables2.out 2>&1

diff $srcdir/otfVariables2.expected otfVariables2.out > /dev/null 2>&1
