#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/AU_and_A_UnificationEdgeCases.maude -no-banner -no-advise \
  > AU_and_A_UnificationEdgeCases.out 2>&1

diff $srcdir/AU_and_A_UnificationEdgeCases.expected AU_and_A_UnificationEdgeCases.out > /dev/null 2>&1
