#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/AU_IrredUnification.maude -no-banner -no-advise \
  > AU_IrredUnification.out 2>&1

diff $srcdir/AU_IrredUnification.expected AU_IrredUnification.out > /dev/null 2>&1
