#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/badView.maude -no-banner -no-advise \
  > badView.out 2>&1

diff $srcdir/badView.expected badView.out > /dev/null 2>&1
