#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/bubble.maude -no-banner -no-advise \
  > bubble.out 2>&1

diff $srcdir/bubble.expected bubble.out > /dev/null 2>&1
