#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/commands.maude -no-banner -no-advise \
  > commands.out 2>&1

diff $srcdir/commands.expected commands.out > /dev/null 2>&1
