#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/CU_Unification.maude -no-banner -no-advise \
  > CU_Unification.out 2>&1

diff $srcdir/CU_Unification.expected CU_Unification.out > /dev/null 2>&1
