#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/debug.maude -no-banner -no-advise \
  > debug.out 2>&1

diff $srcdir/debug.expected debug.out > /dev/null 2>&1
