#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/debug.maude -no-banner \
  > debug.out 2>&1

diff $srcdir/debug.expected debug.out > /dev/null 2>&1
