#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/dekker.maude -no-banner \
  > dekker.out 2>&1

diff $srcdir/dekker.expected dekker.out > /dev/null 2>&1
