#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/dekker.maude -no-banner -no-advise \
  > dekker.out 2>&1

diff $srcdir/dekker.expected dekker.out > /dev/null 2>&1
