set show timing off .

load linear

*** 10 solution system from Domenjoud LNCS 520

red natSystemSolve(
(
(0,0) |-> 1 ; (0,1) |-> 2 ; (0,2) |-> -3 ; (0,3) |-> -2 ; (0,4) |-> -4 ;
(1,0) |-> 2 ; (1,1) |-> -1 ; (1,2) |-> -3 ; (1,3) |-> 2 ; (1,4) |-> 5
),
zeroVector, "cd"
) .

*** sailors and monkey from Contejean and Devie 1994

red natSystemSolve(
(
(0,0) |-> 1 ; (0,1) |-> -5 ;
(1,1) |-> 4 ; (1,2) |-> -5 ;
(2,2) |-> 4 ; (2,3) |-> -5 ;
(3,3) |-> 4 ; (3,4) |-> -5 ;
(4,4) |-> 4 ; (4,5) |-> -5 ;
(5,5) |-> 4 ; (5,6) |-> -5
),
(0 |-> 1 ; 1 |-> 1 ; 2 |-> 1 ; 3 |-> 1 ; 4 |-> 1 ; 5 |-> 1),
"gcd"
) .
