#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/diophantine.maude -no-banner -no-advise \
  > diophantine.out 2>&1

diff $srcdir/diophantine.expected diophantine.out > /dev/null 2>&1
