#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/directoryTest.maude -no-banner -no-advise -allow-dir \
  > directoryTest.out 2>&1

diff $srcdir/directoryTest.expected directoryTest.out > /dev/null 2>&1
