#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/initialEqualityPredicate.maude -no-banner -no-advise \
  > initialEqualityPredicate.out 2>&1

diff $srcdir/initialEqualityPredicate.expected initialEqualityPredicate.out > /dev/null 2>&1
