#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/makeCommand.maude -no-banner -no-advise \
  > makeCommand.out 2>&1

diff $srcdir/makeCommand.expected makeCommand.out > /dev/null 2>&1
