#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/narrow.maude -no-banner -no-advise \
  > narrow.out 2>&1

diff $srcdir/narrow.expected narrow.out > /dev/null 2>&1
