#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/parameterization.maude -no-banner -no-advise \
  > parameterization.out 2>&1

diff $srcdir/parameterization.expected parameterization.out > /dev/null 2>&1
