#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/parameterizedConstant.maude -no-banner -no-advise \
  > parameterizedConstant.out 2>&1

diff $srcdir/parameterizedConstant.expected parameterizedConstant.out > /dev/null 2>&1
