#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/pconst2.maude -no-banner -no-advise \
  > pconst2.out 2>&1

diff $srcdir/pconst2.expected pconst2.out > /dev/null 2>&1
