#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/pconst.maude -no-banner -no-advise \
  > pconst.out 2>&1

diff $srcdir/pconst.expected pconst.out > /dev/null 2>&1
