#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/pconst4.maude -no-banner -no-advise \
  > pconst4.out 2>&1

diff $srcdir/pconst4.expected pconst4.out > /dev/null 2>&1
