#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/printAttributeSelect.maude -no-banner -no-advise \
  > printAttributeSelect.out 2>&1

diff $srcdir/printAttributeSelect.expected printAttributeSelect.out > /dev/null 2>&1
