#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/renaming.maude -no-banner -no-advise \
  > renaming.out 2>&1

diff $srcdir/renaming.expected renaming.out > /dev/null 2>&1
