#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/unification3.maude -no-banner -no-advise \
  > unification3.out 2>&1

diff $srcdir/unification3.expected unification3.out > /dev/null 2>&1
