#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/variantNarrowing.maude -no-banner -no-advise \
  > variantNarrowing.out 2>&1

diff $srcdir/variantNarrowing.expected variantNarrowing.out > /dev/null 2>&1
