#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/checkUnifiers.maude -no-banner -no-advise \
  > checkUnifiers.out 2>&1

diff $srcdir/checkUnifiers.expected checkUnifiers.out > /dev/null 2>&1
