#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/legacyMetaGetVariant.maude -no-banner -no-advise \
  > legacyMetaGetVariant.out 2>&1

diff $srcdir/legacyMetaGetVariant.expected legacyMetaGetVariant.out > /dev/null 2>&1
