#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaTerm.maude -no-banner \
  > metaTerm.out 2>&1

diff $srcdir/metaTerm.expected metaTerm.out > /dev/null 2>&1
