#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcPrelude.maude -no-banner -no-advise \
  > metaProcPrelude.out 2>&1

diff $srcdir/metaProcPrelude.expected metaProcPrelude.out > /dev/null 2>&1
