#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaApply.maude -no-banner -no-advise \
  > metaApply.out 2>&1

diff $srcdir/metaApply.expected metaApply.out > /dev/null 2>&1
