#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaWellFormed.maude -no-banner -no-advise \
  > metaWellFormed.out 2>&1

diff $srcdir/metaWellFormed.expected metaWellFormed.out > /dev/null 2>&1
