#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaIntReplace.maude -no-banner -no-advise \
  > metaIntReplace.out 2>&1

diff $srcdir/metaIntReplace.expected metaIntReplace.out > /dev/null 2>&1
