#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaIntNewNarrow.maude -no-banner -no-advise \
  > metaIntNewNarrow.out 2>&1

diff $srcdir/metaIntNewNarrow.expected metaIntNewNarrow.out > /dev/null 2>&1
