#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaUpModExp.maude -no-banner \
  > metaUpModExp.out 2>&1

diff $srcdir/metaUpModExp.expected metaUpModExp.out > /dev/null 2>&1
