#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaFrewrite.maude -no-banner -no-advise \
  > metaFrewrite.out 2>&1

diff $srcdir/metaFrewrite.expected metaFrewrite.out > /dev/null 2>&1
