#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaParse.maude -no-banner \
  > metaParse.out 2>&1

diff $srcdir/metaParse.expected metaParse.out > /dev/null 2>&1
