#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcReplace2.maude -no-banner -no-advise \
  > metaProcReplace2.out 2>&1

diff $srcdir/metaProcReplace2.expected metaProcReplace2.out > /dev/null 2>&1
