#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcStrategy.maude -no-banner -no-advise \
  > metaProcStrategy.out 2>&1

diff $srcdir/metaProcStrategy.expected metaProcStrategy.out > /dev/null 2>&1
