#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcVariantUnify.maude -no-banner -no-advise \
  > metaProcVariantUnify.out 2>&1

diff $srcdir/metaProcVariantUnify.expected metaProcVariantUnify.out > /dev/null 2>&1
