#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaIntVariantUnify2.maude -no-banner -no-advise \
  > metaIntVariantUnify2.out 2>&1

diff $srcdir/metaIntVariantUnify2.expected metaIntVariantUnify2.out > /dev/null 2>&1
