#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaUp2.maude -no-banner -no-advise \
  > metaUp2.out 2>&1

diff $srcdir/metaUp2.expected metaUp2.out > /dev/null 2>&1
