#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaModExp.maude -no-banner \
  > metaModExp.out 2>&1

diff $srcdir/metaModExp.expected metaModExp.out > /dev/null 2>&1
