#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcNarrowSearch.maude -no-banner -no-advise \
  > metaProcNarrowSearch.out 2>&1

diff $srcdir/metaProcNarrowSearch.expected metaProcNarrowSearch.out > /dev/null 2>&1
