#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcNarrow.maude -no-banner -no-advise \
  > metaProcNarrow.out 2>&1

diff $srcdir/metaProcNarrow.expected metaProcNarrow.out > /dev/null 2>&1
