#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaIntApply.maude -no-banner -no-advise \
  > metaIntApply.out 2>&1

diff $srcdir/metaIntApply.expected metaIntApply.out > /dev/null 2>&1
