#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaIntVariant.maude -no-banner -no-advise \
  > metaIntVariant.out 2>&1

diff $srcdir/metaIntVariant.expected metaIntVariant.out > /dev/null 2>&1
