#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcUnify.maude -no-banner -no-advise \
  > metaProcUnify.out 2>&1

diff $srcdir/metaProcUnify.expected metaProcUnify.out > /dev/null 2>&1
