#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcPrint.maude -no-banner -no-advise \
  > metaProcPrint.out 2>&1

diff $srcdir/metaProcPrint.expected metaProcPrint.out > /dev/null 2>&1
