#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaWellFormed.maude -no-banner \
  > metaWellFormed.out 2>&1

diff $srcdir/metaWellFormed.expected metaWellFormed.out > /dev/null 2>&1
