#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaIntPrelude.maude -no-banner -no-advise \
  > metaIntPrelude.out 2>&1

diff $srcdir/metaIntPrelude.expected metaIntPrelude.out > /dev/null 2>&1
