#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaUp.maude -no-banner \
  > metaUp.out 2>&1

diff $srcdir/metaUp.expected metaUp.out > /dev/null 2>&1
