#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaSpecial.maude -no-banner -no-advise \
  > metaSpecial.out 2>&1

diff $srcdir/metaSpecial.expected metaSpecial.out > /dev/null 2>&1
