#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaPolymorph.maude -no-banner \
  > metaPolymorph.out 2>&1

diff $srcdir/metaPolymorph.expected metaPolymorph.out > /dev/null 2>&1
