#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcVariant.maude -no-banner -no-advise \
  > metaProcVariant.out 2>&1

diff $srcdir/metaProcVariant.expected metaProcVariant.out > /dev/null 2>&1
