#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaIntStrategy.maude -no-banner -no-advise \
  > metaIntStrategy.out 2>&1

diff $srcdir/metaIntStrategy.expected metaIntStrategy.out > /dev/null 2>&1
