#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaReduce.maude -no-banner -no-advise \
  > metaReduce.out 2>&1

diff $srcdir/metaReduce.expected metaReduce.out > /dev/null 2>&1
