#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaUpDown.maude -no-banner \
  > metaUpDown.out 2>&1

diff $srcdir/metaUpDown.expected metaUpDown.out > /dev/null 2>&1
