#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcMatch.maude -no-banner -no-advise \
  > metaProcMatch.out 2>&1

diff $srcdir/metaProcMatch.expected metaProcMatch.out > /dev/null 2>&1
