#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaIntNewNarrowSearch.maude -no-banner -no-advise \
  > metaIntNewNarrowSearch.out 2>&1

diff $srcdir/metaIntNewNarrowSearch.expected metaIntNewNarrowSearch.out > /dev/null 2>&1
