#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaUp.maude -no-banner -no-advise \
  > metaUp.out 2>&1

diff $srcdir/metaUp.expected metaUp.out > /dev/null 2>&1
