#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcParse.maude -no-banner -no-advise \
  > metaProcParse.out 2>&1

diff $srcdir/metaProcParse.expected metaProcParse.out > /dev/null 2>&1
