#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcReplace.maude -no-banner -no-advise \
  > metaProcReplace.out 2>&1

diff $srcdir/metaProcReplace.expected metaProcReplace.out > /dev/null 2>&1
