#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaReduce.maude -no-banner \
  > metaReduce.out 2>&1

diff $srcdir/metaReduce.expected metaReduce.out > /dev/null 2>&1
