#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaMetadata.maude -no-banner -no-advise \
  > metaMetadata.out 2>&1

diff $srcdir/metaMetadata.expected metaMetadata.out > /dev/null 2>&1
