#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaIntParse.maude -no-banner -no-advise \
  > metaIntParse.out 2>&1

diff $srcdir/metaIntParse.expected metaIntParse.out > /dev/null 2>&1
