#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaProcApply.maude -no-banner -no-advise \
  > metaProcApply.out 2>&1

diff $srcdir/metaProcApply.expected metaProcApply.out > /dev/null 2>&1
