#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaModule.maude -no-banner -no-advise \
  > metaModule.out 2>&1

diff $srcdir/metaModule.expected metaModule.out > /dev/null 2>&1
