#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/metaXmatch.maude -no-banner -no-advise \
  > metaXmatch.out 2>&1

diff $srcdir/metaXmatch.expected metaXmatch.out > /dev/null 2>&1
