#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/russianDollsFlat.maude -no-banner -no-advise \
  > russianDollsFlat.out 2>&1

diff $srcdir/russianDollsFlat.expected russianDollsFlat.out > /dev/null 2>&1
