#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/russianDollsFlatProc.maude -no-banner -no-advise \
  > russianDollsFlatProc.out 2>&1

diff $srcdir/russianDollsFlatProc.expected russianDollsFlatProc.out > /dev/null 2>&1
