#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/russianDollsNonFlatProc.maude -no-banner -no-advise \
  > russianDollsNonFlatProc.out 2>&1

diff $srcdir/russianDollsNonFlatProc.expected russianDollsNonFlatProc.out > /dev/null 2>&1
