#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/account.maude -no-banner -no-advise \
  > account.out 2>&1

diff $srcdir/account.expected account.out > /dev/null 2>&1
