#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/dining-philosophers6.maude -no-banner -no-advise \
  > dining-philosophers6.out 2>&1

diff $srcdir/dining-philosophers6.expected dining-philosophers6.out > /dev/null 2>&1
