#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/oo-peg-game2.maude -no-banner \
  > oo-peg-game2.out 2>&1

diff $srcdir/oo-peg-game2.expected oo-peg-game2.out > /dev/null 2>&1
