#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/prngTest.maude -no-banner -no-advise \
  > prngTest.out 2>&1

diff $srcdir/prngTest.expected prngTest.out > /dev/null 2>&1
