#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/rrobin.maude -no-banner -no-advise \
  > rrobin.out 2>&1

diff $srcdir/rrobin.expected rrobin.out > /dev/null 2>&1
