#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/ACU_MissingUnifiersMay2020.maude -no-banner -no-advise \
  > ACU_MissingUnifiersMay2020.out 2>&1

diff $srcdir/ACU_MissingUnifiersMay2020.expected ACU_MissingUnifiersMay2020.out > /dev/null 2>&1
