#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/ascentFunctionsJanuary2020.maude -no-banner -no-advise \
  > ascentFunctionsJanuary2020.out 2>&1

diff $srcdir/ascentFunctionsJanuary2020.expected ascentFunctionsJanuary2020.out > /dev/null 2>&1
