#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/attributeBugsNovember2020.maude -no-banner -no-advise \
  > attributeBugsNovember2020.out 2>&1

diff $srcdir/attributeBugsNovember2020.expected attributeBugsNovember2020.out > /dev/null 2>&1
