#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/closeSocketFeb2020.maude -no-banner -no-advise \
  > closeSocketFeb2020.out 2>&1

diff $srcdir/closeSocketFeb2020.expected closeSocketFeb2020.out > /dev/null 2>&1
