#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/complexParserSyncApril2020.maude -no-banner -no-advise \
  > complexParserSyncApril2020.out 2>&1

diff $srcdir/complexParserSyncApril2020.expected complexParserSyncApril2020.out > /dev/null 2>&1
