#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/CUI_OccursCheckSeptember2020.maude -no-banner -no-advise \
  > CUI_OccursCheckSeptember2020.out 2>&1

diff $srcdir/CUI_OccursCheckSeptember2020.expected CUI_OccursCheckSeptember2020.out > /dev/null 2>&1
