#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/CUIbug12-22-09.maude -no-banner -no-advise \
  > CUIbug12-22-09.out 2>&1

diff $srcdir/CUIbug12-22-09.expected CUIbug12-22-09.out > /dev/null 2>&1
