#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/deleteTimerMarch2021.maude -no-banner -no-advise \
  > deleteTimerMarch2021.out 2>&1

diff $srcdir/deleteTimerMarch2021.expected deleteTimerMarch2021.out > /dev/null 2>&1
