#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/doubleAttributeFebruary2023.maude -no-banner \
  > doubleAttributeFebruary2023.out 2>&1

diff $srcdir/doubleAttributeFebruary2023.expected doubleAttributeFebruary2023.out > /dev/null 2>&1
