#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/filteredVariantUnifyJune2023.maude -no-banner \
  > filteredVariantUnifyJune2023.out 2>&1

diff $srcdir/filteredVariantUnifyJune2023.expected filteredVariantUnifyJune2023.out > /dev/null 2>&1
