#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/instantiationJuly2019.maude -no-banner -no-advise \
  > instantiationJuly2019.out 2>&1

diff $srcdir/instantiationJuly2019.expected instantiationJuly2019.out > /dev/null 2>&1
