#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/instantiatedViewInternalNameOctober2022.maude -no-banner -no-advise \
  > instantiatedViewInternalNameOctober2022.out 2>&1

diff $srcdir/instantiatedViewInternalNameOctober2022.expected instantiatedViewInternalNameOctober2022.out > /dev/null 2>&1
