#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/irredUnifyFeb2021.maude -no-banner -no-advise \
  > irredUnifyFeb2021.out 2>&1

diff $srcdir/irredUnifyFeb2021.expected irredUnifyFeb2021.out > /dev/null 2>&1
