#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/kindNameDecember2022.maude -no-banner -no-advise \
  > kindNameDecember2022.out 2>&1

diff $srcdir/kindNameDecember2022.expected kindNameDecember2022.out > /dev/null 2>&1
