#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaModuleCacheJune2018.maude -no-banner -no-advise \
  > metaModuleCacheJune2018.out 2>&1

diff $srcdir/metaModuleCacheJune2018.expected metaModuleCacheJune2018.out > /dev/null 2>&1
