#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaNarrowingApplyMarch2023.maude -no-banner -no-advise \
  > metaNarrowingApplyMarch2023.out 2>&1

diff $srcdir/metaNarrowingApplyMarch2023.expected metaNarrowingApplyMarch2023.out > /dev/null 2>&1
