#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaIntMatchOct2018.maude -no-banner -no-advise \
  > metaIntMatchOct2018.out 2>&1

diff $srcdir/metaIntMatchOct2018.expected metaIntMatchOct2018.out > /dev/null 2>&1
