#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaParseStrategyApril2020.maude -no-banner -no-advise \
  > metaParseStrategyApril2020.out 2>&1

diff $srcdir/metaParseStrategyApril2020.expected metaParseStrategyApril2020.out > /dev/null 2>&1
