#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/metaAutoOoIncludeFebruary2023.maude -no-banner -no-advise \
  > metaAutoOoIncludeFebruary2023.out 2>&1

diff $srcdir/metaAutoOoIncludeFebruary2023.expected metaAutoOoIncludeFebruary2023.out > /dev/null 2>&1
