#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/orphanedViewInstantiationFebruary2023.maude -no-banner -no-advise \
  > orphanedViewInstantiationFebruary2023.out 2>&1

diff $srcdir/orphanedViewInstantiationFebruary2023.expected orphanedViewInstantiationFebruary2023.out > /dev/null 2>&1
