#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/parameterizedPolymorphicConstantMarch2023.maude -no-banner -no-advise \
  > parameterizedPolymorphicConstantMarch2023.out 2>&1

diff $srcdir/parameterizedPolymorphicConstantMarch2023.expected parameterizedPolymorphicConstantMarch2023.out > /dev/null 2>&1
