#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/parameterTheoryMay2019.maude -no-banner -no-advise \
  > parameterTheoryMay2019.out 2>&1

diff $srcdir/parameterTheoryMay2019.expected parameterTheoryMay2019.out > /dev/null 2>&1
