#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/parameterTheoryCopyMay2019.maude -no-banner -no-advise \
  > parameterTheoryCopyMay2019.out 2>&1

diff $srcdir/parameterTheoryCopyMay2019.expected parameterTheoryCopyMay2019.out > /dev/null 2>&1
