#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/physArgIndexOct2018.maude -no-banner -no-advise \
  > physArgIndexOct2018.out 2>&1

diff $srcdir/physArgIndexOct2018.expected physArgIndexOct2018.out > /dev/null 2>&1
