#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/pseudoParameterTheoryConstantMarch2023.maude -no-banner -no-advise \
  > pseudoParameterTheoryConstantMarch2023.out 2>&1

diff $srcdir/pseudoParameterTheoryConstantMarch2023.expected pseudoParameterTheoryConstantMarch2023.out > /dev/null 2>&1
