#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/quotedTokenMarch2023.maude -no-banner -no-advise \
  > quotedTokenMarch2023.out 2>&1

diff $srcdir/quotedTokenMarch2023.expected quotedTokenMarch2023.out > /dev/null 2>&1
