#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/redBlackNonLinearApril2023.maude -no-banner -no-advise \
  > redBlackNonLinearApril2023.out 2>&1

diff $srcdir/redBlackNonLinearApril2023.expected redBlackNonLinearApril2023.out > /dev/null 2>&1
