#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/redBlackNGA_April2023.maude -no-banner -no-advise \
  > redBlackNGA_April2023.out 2>&1

diff $srcdir/redBlackNGA_April2023.expected redBlackNGA_April2023.out > /dev/null 2>&1
