#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/redBlackTooFewSubjectsApril2023.maude -no-banner -no-advise \
  > redBlackTooFewSubjectsApril2023.out 2>&1

diff $srcdir/redBlackTooFewSubjectsApril2023.expected redBlackTooFewSubjectsApril2023.out > /dev/null 2>&1
