#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/showDesugaredFebruary2023.maude -no-banner \
  > showDesugaredFebruary2023.out 2>&1

diff $srcdir/showDesugaredFebruary2023.expected showDesugaredFebruary2023.out > /dev/null 2>&1
