#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/showModuleJune2018.maude -no-banner -no-advise \
  > showModuleJune2018.out 2>&1

diff $srcdir/showModuleJune2018.expected showModuleJune2018.out > /dev/null 2>&1
