#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/smodStrategyNameJanuary2023.maude -no-banner \
  > smodStrategyNameJanuary2023.out 2>&1

diff $srcdir/smodStrategyNameJanuary2023.expected smodStrategyNameJanuary2023.out > /dev/null 2>&1
