#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/specificOpMappingPrintFebruary2023.maude -no-banner -no-advise \
  > specificOpMappingPrintFebruary2023.out 2>&1

diff $srcdir/specificOpMappingPrintFebruary2023.expected specificOpMappingPrintFebruary2023.out > /dev/null 2>&1
