#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/spuriousAdvisoryRenamingCaptureJanuary2023.maude -no-banner \
  > spuriousAdvisoryRenamingCaptureJanuary2023.out 2>&1

diff $srcdir/spuriousAdvisoryRenamingCaptureJanuary2023.expected spuriousAdvisoryRenamingCaptureJanuary2023.out > /dev/null 2>&1
