#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/stratToExprNotValidMay2025.maude -no-banner -no-advise \
  > stratToExprNotValidMay2025.out 2>&1

diff $srcdir/stratToExprNotValidMay2025.expected stratToExprNotValidMay2025.out > /dev/null 2>&1
