#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/stripperCollectorSwitchMay2023.maude -no-banner \
  > stripperCollectorSwitchMay2023.out 2>&1

diff $srcdir/stripperCollectorSwitchMay2023.expected stripperCollectorSwitchMay2023.out > /dev/null 2>&1
