#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/theoryViewOpToTermFebruary2023.maude -no-banner -no-advise \
  > theoryViewOpToTermFebruary2023.out 2>&1

diff $srcdir/theoryViewOpToTermFebruary2023.expected theoryViewOpToTermFebruary2023.out > /dev/null 2>&1
