#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/uninitIterExtSeptember2021.maude -no-banner -no-advise \
  > uninitIterExtSeptember2021.out 2>&1

diff $srcdir/uninitIterExtSeptember2021.expected uninitIterExtSeptember2021.out > /dev/null 2>&1
