#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/upTheoryJanuary2023.maude -no-banner -no-advise \
  > upTheoryJanuary2023.out 2>&1

diff $srcdir/upTheoryJanuary2023.expected upTheoryJanuary2023.out > /dev/null 2>&1
