#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/variantUnifyJune2020.maude -no-banner -no-advise \
  > variantUnifyJune2020.out 2>&1

diff $srcdir/variantUnifyJune2020.expected variantUnifyJune2020.out > /dev/null 2>&1
