#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude -no-prelude \
  < $srcdir/viewInstantiationByTheoryViewStrategyMay2025.maude -no-banner -no-advise \
  > viewInstantiationByTheoryViewStrategyMay2025.out 2>&1

diff $srcdir/viewInstantiationByTheoryViewStrategyMay2025.expected viewInstantiationByTheoryViewStrategyMay2025.out > /dev/null 2>&1
