#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/counters.maude -no-banner -no-advise \
  > counters.out 2>&1

diff $srcdir/counters.expected counters.out > /dev/null 2>&1
