#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/nat.maude -no-banner -no-advise \
  > nat.out 2>&1

diff $srcdir/nat.expected nat.out > /dev/null 2>&1
