#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/stringOps.maude -no-banner -no-advise \
  > stringOps.out 2>&1

diff $srcdir/stringOps.expected stringOps.out > /dev/null 2>&1
