#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Mixfix
export MAUDE_LIB

../../src/Mixfix/maude \
  < $srcdir/string.maude -no-banner \
  > string.out 2>&1

diff $srcdir/string.expected string.out > /dev/null 2>&1
